### ISSUE TITLE
After C# upgrade to 2.1.32 constantly getting disconnects on Raspberry PI

### ISSUE THREAD

**Issue by ChristianRiedl** [Tinkerforge/generators#61] opened 2024-03-28 16:53 UTC
I use a .NET 8.0 ASP Net Core application on a Raspberry PI 3 (Raspbian bullseye, 32 bit).

After upgrading the Tinkerforge API from 2.1.31 to 2.1.32 I get permanently disconnects (several times per second).  

The problem does not occur when running on Windows.

In **brickd.log** I find quite often (for every disconnect) :

`2024-03-28 17:25:12.814733 <I> <client.c:263> Client (N: 192.168.1.205:45274, T: plain-socket, H: 23/23, B: 0, P: 0, A: disabled) disconnected by peer`

I guess the problem is related with the latest fix **"Fix System.AppDomain.Unload timeout"**.

**Comment by photron** [comment] 2024-04-02 15:22
I have an idea where this problem might come from. I think you are right about the fix for System.AppDomain.Unload timeout. I will look at this. Thank you for reporting this problem.

**Comment by photron** [comment] 2024-04-02 16:16
Please try the attached C# bindings version. Microsoft's and Mono's .NET runtime on Linux use different error codes to indicate a socket read timeout. The C# bindings only handled Mono's error code 10035, but not Microsoft's error code 110. This is fixed now and I cannot reproduce the problem anymore.

[tinkerforge_csharp_bindings_2_1_33_rc1.zip](https://github.com/Tinkerforge/generators/files/14840197/tinkerforge_csharp_bindings_2_1_33_rc1.zip)

**Comment by ChristianRiedl** [comment] 2024-04-02 17:14
Matthias,

this new version (2.1.33.rc1) fixes the problem !

Christian

Von: Matthias Bolte ***@***.***>
Gesendet: Dienstag, 2. April 2024 18:17
An: Tinkerforge/generators ***@***.***>
Cc: RTS Christian Riedl ***@***.***>; Author ***@***.***>
Betreff: Re: [Tinkerforge/generators] After C# upgrade to 2.1.32 constantly getting disconnects on Raspberry PI (Issue #61)


Please try the attached C# bindings version. Microsoft's and Mono's .NET runtime on Linux use different error codes to indicate a socket read timeout. The C# bindings only handled Mono's error code 10035, but not Microsoft's error code 110. This is fixed now and I cannot reproduce the problem anymore.

tinkerforge_csharp_bindings_2_1_33_rc1.zip<https://github.com/Tinkerforge/generators/files/14840197/tinkerforge_csharp_bindings_2_1_33_rc1.zip>

**Closed** 2024-04-09 13:35 UTC
